api_platform:
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats: 
        jsonld:   ['application/ld+json']
        json:     ['application/json']
        html:     ['text/html']
    patch_formats:
        json:     ['application/merge-patch+json']
        jsonapi:  ['application/vnd.api+json']
    swagger:
        versions: [3]
    description: 'Test de API Platform'
