<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMHCEo1x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMHCEo1x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMHCEo1x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMHCEo1x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMHCEo1x\App_KernelDevDebugContainer([
    'container.build_hash' => 'MHCEo1x',
    'container.build_id' => '73aca960',
    'container.build_time' => 1648138124,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMHCEo1x');
